name: CI/CD production
on:
  push:
    branches:
      - master


jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: installing NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm install
        working-directory: ./client
        

      - name: Building the App
        run: npm run build
        working-directory: ./client
        env:
          CI: false

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa anthony-kalbe.fr >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: anthony-kalbe.fr

      
      

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@6.0.0 
        with:
          switches: -avzr --delete
          remote_path: /var/www/html/chat/
          remote_host: anthony-kalbe.fr
          remote_user: sftpuser

      
      - name: Upload with rsync
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./client/build/ sftpuser@anthony-kalbe.fr:/var/www/html/chat/


          

          

        
        






            

            