name: CI/CD production
on:
  push:
    branches:
      - master


jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: installing NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm install
        working-directory: ./client
        

      - name: Building the App
        run: npm run build
        working-directory: ./client
        env:
          CI: false

      - name: deploy rsync to server
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        with:
            flags: '-zvr'
            options: '-O'
            src: './client/build/'
            dest: 'root@anthony-kalbe.fr:/var/www/html/chat/client/'

      - name: deploy the server
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        with:
            flags: '-zvr'
            options: '-O'
            src: './server/'
            dest: 'root@anthony-kalbe.fr:/var/www/html/chat/server/'
          

          

        
        






            

            