name: CI/CD production
on:
  push:
    branches:
      - master


jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: installing NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm install
        working-directory: ./client
        

      - name: Building the App
        run: npm run build
        working-directory: ./client
        env:
          CI: false

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@4.1.0
        with:
          switches: -avzr --delete
          path: ./client/build/
          remote_path: /var/www/html/chat
          remote_host: anthony-kalbe.fr
          remote_user: root
          remote_key: AAAAB3NzaC1yc2EAAAADAQABAAABAQCzLm+dHNm9ZzNz4ldaKhbJjrPoahQlp/FNT7wYcKF6zV30rTB8Oz6tooojEXgsIioR8KqGs7PxqIX30xxsoII0LNZqQDvcm4xBo6zzPX/gSkmaantzbjeLR7hT08eUXFoERNAMs3Aa1P4N5V752oj70Fol+AIHY0kLd8rFsO7we9n9taTXXRNjWUjFSVYQCKpuUAwQ67IYklvp0HbLwtR8r8zNo8ksFGAZN4BTRjPiWF704tiZBdJyUe/Ycgirbwyl/kAonUPR/wX5KEeWc6vbTVwR6CHkW5NdPd1d92BXB6VpSy9724q8prh4P3164JxdaWCW/PYT99NcrDcwW0VL
        
        






            

            